services:
  web:
    image: lalithamangalamm/kamal-spike-run
    ports:
      - "3000:80"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    secrets:
      - rails_master_key

secrets:
  rails_master_key:
    file: ./config/master.key
