service: kamal_spike_run

image: lalithamangalamm/kamal_spike_run

servers:
  web:
    - 13.235.128.28

proxy:
  ssl: false
  host: 13.235.128.28

registry:
  username: lalithamangalamm
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: ubuntu
  keys:
    - .kamal/github_actions_key
tag:
  - <%= ENV["IMAGE_TAG"] %>
