# Name of your application
service: kamal_spike_run

# Name of the container image
image: lalithamangalamm/kamal_spike_run

# Credentials for your image host
registry:
  username: lalithamangalamm
  password:
    - KAMAL_REGISTRY_PASSWORD

# Deploy to these servers
servers:
  web:
    - 52.66.133.94
  worker:
    hosts:
      - 65.2.132.112
    cmd: bundle exec sidekiq

# Proxy configuration
proxy:
  ssl: false
  host: 52.66.133.94

# Environment variables
env:
  clear:
    ENVIRONMENT: staging
    SERVER_IP: "%h"
  secret:
    - DATABASE_URL
    - RAILS_MASTER_KEY
    - REDIS_URL

# Asset bridging between deployments
asset_path: /rails/public/assets

# Configure image builder
builder:
  arch: amd64


# SSH settings
# Note: For local commands to work, use standard local keys or remove `keys:` if using default ~/.ssh/id_rsa/ed25519
ssh:
  user: ubuntu

# Command aliases
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  staging-logs: app logs -d staging -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
