name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image SHA to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      - name: Login Docker
        run: |
          echo "${{ secrets.KAMAL_REGISTRY_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Deploy Production
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          kamal deploy -d production
