name: Deploy Rails App

on:
  push:
    branches:
      - main

jobs:
  # ----------------------------------------------------
  # JOB 1: Build Image + Deploy to Staging
  # ----------------------------------------------------
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    outputs:
      image_tag: ${{ steps.image.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.1"
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.KAMAL_REGISTRY_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Setup SSH key
        run: |
          mkdir -p .kamal
          echo "${{ secrets.EC2_SSH_KEY }}" > .kamal/github_actions_key
          chmod 600 .kamal/github_actions_key

      # Save the image tag (Git SHA)
      - name: Save image tag
        id: image
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to Staging
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          KAMAL_VERSION: ${{ github.sha }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          kamal deploy -d staging

  # ----------------------------------------------------
  # JOB 2: Deploy SAME image to Production
  # ----------------------------------------------------
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest

    # GitHub pauses here waiting for approval
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.1"
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.KAMAL_REGISTRY_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to Production
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          KAMAL_VERSION: ${{ needs.deploy-staging.outputs.image_tag }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          kamal deploy -d production --skip-push
